### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by MohamedElashri** [Creator-SN/MathX#1]
Hi 

I'm interested in using this app, I tried to build it on my MacBook m1 but after the build the app just shows blank page and fail to load all `css` files. 

I would like to know if you tested build on Mac and if so can you add `dmg` to the releases?

**Comment by minskiter** [comment]
We will add a new release when we test successfully on the mac. Thanks for the support!

**Comment by minskiter** [comment]
We could't build binary on m1 machine because github action(Azure) cannot support arm64 macos.. https://github.com/actions/virtual-environments/issues/2552

**Comment by MohamedElashri** [comment]
Thank you for the release, the `x64` version works on m1 via Rosetta emulator. If I tried to build locally I have to change to electron `11.0.0` because this is the first electron version that supports `arm` it builds but no CSS loading or anything. 

So it is more than GitHub providing `arm`, there should be some changes. Hopefully in the future.

**Comment by MohamedElashri** [comment]
Thank you for the release, the `x64` version works on m1 via Rosetta emulator. If I tried to build locally I have to change to electron `11.0.0` because this is the first electron version that supports `arm` it builds but no CSS loading or anything. 

So it is more than GitHub providing `arm`, there should be some changes. Hopefully in the future.
