### ISSUE TITLE
有时截屏识别无反应

### ISSUE THREAD

**Issue by ziguozhao** [Creator-SN/MathX#2]
感谢作者开发出这款软件，目前使用时会遇到截屏有时无法正常使用，还有就是copy microsoft word 创建的omml公式无法进行公式编辑

**Comment by minskiter** [comment]
您好！关于截图无法使用主要是在哪些场景呢？

**Comment by ziguozhao** [comment]
> 您好！关于截图无法使用主要是在哪些场景呢？

不知道是不是我系统软件过多导致，后台运行了PandaOCR和Snipaste，刚才我测试时就出现了不同的bug：要么出现了截图的光标但没法截图，要么是不弹出截图，多重试几次后功能就稳定了。针对copy microsoft word 创建的omml公式无法进行公式编辑的问题不知有考虑改进吗？不知后期能考虑自定义快捷键吗？建议加上打赏码

**Comment by minskiter** [comment]
针对目前存在的截图功能，截图组件目前使用的是第三方开源组件，启动与关闭可能存在较为严重的延迟，因此我们将在后续版本针对该问题尽可能的进行修复。
针对copy microsoft word 创建的omml公式无法进行公式编辑的问题——该功能经测试在最新版本2110的microsoft word 365中是允许进行编辑的；
![image](https://user-images.githubusercontent.com/23184022/141646352-dcf0101f-dfde-4424-8dce-0c92a831b4ca.png)
感谢您的支持！

**Comment by ziguozhao** [comment]
> 针对目前存在的截图功能，截图组件目前使用的是第三方开源组件，启动与关闭可能存在较为严重的延迟，因此我们将在后续版本针对该问题尽可能的进行修复。 针对copy microsoft word 创建的omml公式无法进行公式编辑的问题——该功能经测试在最新版本2110的microsoft word 365中是允许进行编辑的； ![image](https://user-images.githubusercontent.com/23184022/141646352-dcf0101f-dfde-4424-8dce-0c92a831b4ca.png) 感谢您的支持！

感谢，可能是office2019的原因吧，其它地方没什么缺点，很好的产品
