### ISSUE TITLE
Is it possible to support Mac Intel?

### ISSUE THREAD

**Issue by wenlzhang** [Creator-SN/MathX#4]
Currently, Mac ARM 64 is support. It would be great if Mac Intel can also be supported.

**Comment by minskiter** [comment]
Thank you for your feedback.  The mac version is compiled for x64. I think it's supported.

**Comment by wenlzhang** [comment]
I have macOS 13.1. When clicking the scan button, nothing happens.
![CleanShot 2022-11-02 at 16 33 04](https://user-images.githubusercontent.com/44930227/199532465-864993ab-ed07-499b-af98-d6e8fff16787.gif)

**Comment by aleversn** [comment]
App has supported mac intel.
